### ISSUE TITLE
http://emf-rest.com/ does not resolve.

### ISSUE THREAD

**Issue by sbronner** [SOM-Research/emf-rest#16]
It's the first link in the README - should it be https://som-research.uoc.edu/tools/emf-rest/?

**Comment by hamzaed** [comment]
Hi, 
Thank you for your feedback!
EMF-REST is now hosted in a subfolder of the website of our team (the one you mentioned: https://som-research.uoc.edu/tools/emf-rest/) so we created an automatic redirection from http://emf-rest.com/ to the new domain. I don't see any problem here.

Hamza

**Comment by sbronner** [comment]
Looks like it's resolving now - apologies, it wasn't for a couple of days. Maybe a dns propagation issue in Australia!
